backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'supervisors'
    label: 'Supervisors'
    folder: '_supervisors/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'supervisor' }
      - { label: 'Name', name: 'name', widget: 'string' }
